### ISSUE TITLE
Really wierd glitch I dont know how to title this

### ISSUE THREAD

**Issue by Talci** [mcbrawls/brawls-issues#10]
![image](https://github.com/mcbrawls/brawls-issues/assets/134812575/743c5d50-7561-40a5-924b-3ca407fca08f)
when you queue rise in a party then invite people you are in the rise queue but you cannot leave the rise queue and if someone queues you accually teleport to rise

**Comment by andantet** [comment]
Invalid issue in-dev, queue system is being rebuilt
