### ISSUE TITLE
Resource Pack Disconnect doesn't work

### ISSUE THREAD

**Issue by MacStevins** [mcbrawls/brawls-issues#13]
When joining the server and the game asking you to download the resource pack, if you picked no, the game doesn't kick you out of the server.

This puts you into a limbo-like state where you're still in the server and your player entity can be seen by others, but chat, commands, and even falling off the void and teleporting back doesn't work. Players have said that you're not even in the tab menu.

**Comment by andantet** [comment]
Are you using a modded client? I've just tested this and it works perfectly as intended.

As a reassurance, any issue like this is fixed for the next major release.

## Walkthrough

- Join server

![image](https://github.com/mcbrawls/brawls-issues/assets/36608902/9afa7cde-faaf-42ed-bf10-d3c4794876e3)

- Click disconnect button

![image](https://github.com/mcbrawls/brawls-issues/assets/36608902/382fdc31-0a33-4217-b691-72ce38964bb2)

**Comment by MacStevins** [comment]
I am using a modded client, Quilt, with these mods enabled

- Alternate Current
- AppleSkin
- Bad Packets
- Better Advancements
- Better Beds
- BetterF3
- Concurrent Chunk Management Engine
- Chat Heads
- CIT Resewn
- Cloth Config API
- Controlling
- DashLoader
- Dynamic FPS
- Eating Animation
- Entity Culling
- Exordium
- FastAnim
- Fastload
- FerriteCore
- Freecam
- ImmediatelyFast
- Indium
- Inventory HUD+
- Iris
- Island Utils
- Krypton
- LambDynamicLights
- LazyDFU
- Lithium
- Logical Zoom
- MaLiLib
- MCCI: Companion
- Memory Leak Fix
- MidnightControls
- MiniHUD
- Mod Menu
- More Culling
- Mouse Tweaks
- Noxesium
- Quilt Kotlin Libraries (QKL)
- Quilted Fabric API
- Reese's Sodium Options
- ReplayMod
- ResolutionControl+
- Searchables
- ServerCore
- Server Pack Unlocker (sometimes used, but even without, it still happens)
- Sodium Extra
- Sodium
- Sodium Shadowy Path Blocks
- spark
- Starlight (Fabric)
- Very Many Players
- YetAnotherConfigLib

Playing on the same instance without mods does give the output that you have

**Comment by andantet** [comment]
I'm aware of issues on Brawls to do with Immediately Fast, see this announcement:

![image](https://github.com/mcbrawls/brawls-issues/assets/36608902/60eed5b6-1d08-4d6b-abb9-bea04aa5e13a)

I'm not sure that Immediately Fast would cause the issues you have described, though. Try removing half of your mods at a time until you find an offending mod.

**Comment by MacStevins** [comment]
So, I checked all of my mods, and Replay Mod, version 1.20.1-2.6.13, made the server resource pack disconnect bug a thing, also I didn't got any errors on Immediately Fast, just low frame rates, but that's on my system
