### ISSUE TITLE
Scrolling is weird and glitchy in 0.6.11

### ISSUE THREAD

**Issue by Lavaburgs** [mcbrawls/brawls-issues#16]
Scrolling to multiple hotbar slots rapidly makes the hotbar freak out and glitch between 2 (and sometimes 3) slots.

**Comment by radstevee** [comment]
Do you have any video footage of this?

**Comment by Kiqsk** [comment]
https://github.com/user-attachments/assets/4200551a-3e6c-4681-a601-d0af5bd49704

**Comment by andantet** [comment]
This was an issue a while back and I made a change in 0.6.10 which played around with the fix for that issue.

I'll take a look.

**Comment by andantet** [comment]
Fixed in 0.6.12
